system:
  name: "FairManServer"
  port: 8888
  version: "v0.0.1"
zap:
  level: info
  format: console
  prefix: '[FAIR-MAN-SERVER]'
  directory: log
  link-name: latest_log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
